apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: localhost/enterprise-microservices-app_order-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: "100m"
              memory: "120Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: localhost/enterprise-microservices-app_payment-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: localhost/enterprise-microservices-app_inventory-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: localhost/enterprise-microservices-app_notification-service:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: discord-secret
